apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: timestamp-authority-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: timestamp-authority-1-0-gamma
    app.kubernetes.io/part-of: tsa-1-0-gamma
  name: timestamp-authority-1-0-gamma
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: timestamp-authority-1-0-gamma
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: timestamp-authority-1-0-gamma
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/tsa-1-0-gamma/timestamp-authority-1-0-gamma@sha256:9b4af37245858e6a58359d2db5a8726069c94f56544cb8239c2559cd72a9de9e
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 2997
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
