apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: timestamp-authority-1-0-gamma
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: timestamp-authority-1-0-gamma
    app.kubernetes.io/part-of: tsa-1-0-gamma
  name: timestamp-authority-1-0-gamma
spec:
  ports:
  - port: 2997
    targetPort: 2997
  selector:
    app.kubernetes.io/instance: timestamp-authority-1-0-gamma
status:
  loadBalancer: {}
